# Git shortcuts
abbr g 'git'
abbr ga 'git add'
abbr gs 'git status'
abbr gc 'git commit'
abbr gcm 'git commit -m'
abbr gca 'git commit --amend'
abbr gp 'git push'
abbr gpf 'git push --force'
abbr gl 'git log --oneline --graph'
abbr gb 'git branch'
abbr gco 'git checkout'
abbr gcb 'git checkout -b'
abbr gm 'git merge'
abbr gr 'git rebase'
abbr grc 'git rebase --continue'
abbr grs 'git reset'
abbr grh 'git reset --hard'
abbr gcl 'git clone'

# Bonus time-savers
abbr gst 'git stash'
abbr gstp 'git stash pop'
abbr gpl 'git pull'
abbr gf 'git fetch'
abbr gfa 'git fetch --all'
